---
- name: debian | update package list
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: debian | installing pre-reqs
  apt:
    name: "{{ mariadb_pre_req_packages }}"
    state: "present"
  become: true
  loop:

- name: debian | adding Repo Keys
  apt_key:
    keyserver: "{{ debian_repo_keyserver }}"
    id: "{{ debian_repo_key }}"
    state: "present"
  become: true
  when: galera_enable_mariadb_repo|bool and not debian_repo_key_url is defined

- name: debian | adding Repo Keys
  apt_key:
    url: "{{ debian_repo_key_url }}"
    state: "present"
  become: true
  when: galera_enable_mariadb_repo|bool and debian_repo_key_url is defined

- name: debian | pinning MariaDB Repo
  template:
    src: "etc/apt/preferences.d/mariadb.j2"
    dest: "/etc/apt/preferences.d/mariadb"
    mode: "0644"
  become: true
  when: vendor == 'mariadb' and galera_enable_mariadb_repo|bool

- name: debian | pinning MySQL Repo
  template:
    src: "etc/apt/preferences.d/mysql.j2"
    dest: "/etc/apt/preferences.d/mysql"
    mode: "0644"
  become: true
  when: vendor == 'mysql' and galera_enable_mariadb_repo|bool

- name: debian | adding MariaDB repo
  apt_repository:
    repo: "{{ mariadb_debian_repo }}"
    state: "present"
  become: true
  when: vendor == 'mariadb' and galera_enable_mariadb_repo|bool

- name: debian | adding MySQL repo
  apt_repository:
    repo: "{{ mysql_debian_repo }}"
    state: "present"
  become: true
  when: vendor == 'mysql' and galera_enable_mariadb_repo|bool

- name: debian | adding Galera repo
  apt_repository:
    repo: "{{ galera_debian_repo }}"
    state: "present"
  become: true
  when: vendor == 'mysql' and galera_enable_mariadb_repo|bool

- name: debian | precreate /etc/mysql/conf.d in case we need to add mariadb_config_overrides file
  file:
    path: "/etc/mysql/conf.d"
    state: "directory"
    mode: 0755
  become: true
  when: mariadb_config_overrides is defined

- name: debian | add an overrides file
  template:
    src: "etc/mariadb_overrides.cnf.j2"
    dest: "/etc/mysql/conf.d/overrides.cnf"
    mode: "0644"
  become: true
  when: mariadb_config_overrides is defined

- name: debian | installing mariadb-galera packages
  apt:
    name: "{{ (galera_sst_method == 'mariabackup') | ternary( mariadb_packages | union( mariabackup_packages ), mariadb_packages ) }}"
    state: "present"
  become: true
  when: vendor == 'mariadb'

- name: debian | installing mysql-galera packages
  apt:
    name: "{{ mysql_packages }}"
    state: "present"
  become: true
  when: vendor == 'mysql'

- name: debian | verify apparmor profile is disabled
  command:
    cmd: "stat /etc/apparmor.d/disable/usr.sbin.mysqld"
  become: true
  register: mysqld_apparmor_profile
  when: vendor == 'mysql'
  failed_when: false
  changed_when: false

- name: debian | disable apparmor profile
  command:
    cmd: "ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/usr.sbin.mysqld"
  become: true
  when: vendor == 'mysql' and mysqld_apparmor_profile.rc != 0
  changed_when: false

- name: debian | remove apparmor profile
  command:
    cmd: "apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld"
  become: true
  register: mysqld_apparmor_remove
  when: vendor == 'mysql' and mysqld_apparmor_profile.rc != 0
  changed_when: mysqld_apparmor_remove.rc == 0
  failed_when: mysqld_apparmor_remove.rc != 0 and mysqld_apparmor_remove.rc != 254
